version: '3.7'


services:
  web:
    build:
      context: app/dockerFiles/nginx
    #    uncommented this line if you have apple silicon proc
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP:-host.docker.internal}
    volumes:
      - ./:/projectX
    depends_on:
      - php
      - mysql

  php:
    build: ./app/DockerFiles/php
    container_name: php_test
    volumes:
      - ./:/projectX
      - ./app/DockerFiles/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./app/DockerFiles/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    expose:
      - 9000


  mysql:
    #    uncommented this line if you have apple silicon proc
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./app/db/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitMq
    ports:
      - "15671:15671"
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "WHATISTHISCOOKIEANDWHY"
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmqpass
      RABBITMQ_DEFAULT_VHOST: "/"


  phpmyadmin:
    #    uncommented this line if you have apple silicon proc
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
